[2025-03-09T23:45:34.448+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T23:45:34.461+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T17:45:10.269297+00:00 [queued]>
[2025-03-09T23:45:34.470+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T17:45:10.269297+00:00 [queued]>
[2025-03-09T23:45:34.470+0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T23:45:34.600+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-03-09 17:45:10.269297+00:00
[2025-03-09T23:45:34.611+0600] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-09T23:45:34.619+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_e2e_dag', 'extract_data_task', 'manual__2025-03-09T17:45:10.269297+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/RT_temp.py', '--cfg-path', '/tmp/tmp3hz_w800']
[2025-03-09T23:45:34.620+0600] {standard_task_runner.py:105} INFO - Job 15: Subtask extract_data_task
[2025-03-09T23:45:34.626+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=33858) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-09T23:45:34.627+0600] {standard_task_runner.py:72} INFO - Started process 34025 to run task
[2025-03-09T23:45:34.669+0600] {task_command.py:467} INFO - Running <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T17:45:10.269297+00:00 [running]> on host shamim-X541UV
[2025-03-09T23:45:34.743+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_e2e_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T17:45:10.269297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T17:45:10.269297+00:00'
[2025-03-09T23:45:34.745+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T23:45:34.745+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T23:45:34.745+0600] {logging_mixin.py:190} INFO - Current task name:extract_data_task state:running start_date:2025-03-09 17:45:34.461914+00:00
[2025-03-09T23:45:34.745+0600] {logging_mixin.py:190} INFO - Dag name:real_time_e2e_dag and current dag run status:running
[2025-03-09T23:45:34.746+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T23:45:39.124+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_temp.py", line 48, in extract_data
    pandas_df = parsed_df.toPandas()
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/pandas/conversion.py", line 86, in toPandas
    require_minimum_pandas_version()
  File "/home/shamim/spark/python/pyspark/sql/pandas/utils.py", line 24, in require_minimum_pandas_version
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
[2025-03-09T23:45:39.142+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T23:45:39.142+0600] {logging_mixin.py:190} INFO - Task start:2025-03-09 17:45:34.461914+00:00 end:2025-03-09 17:45:39.141319+00:00 duration:4.679405
[2025-03-09T23:45:39.143+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_task> dag:<DAG: real_time_e2e_dag> dagrun:<DagRun real_time_e2e_dag @ 2025-03-09 17:45:10.269297+00:00: manual__2025-03-09T17:45:10.269297+00:00, state:running, queued_at: 2025-03-09 17:45:10.300529+00:00. externally triggered: True>
[2025-03-09T23:45:39.143+0600] {logging_mixin.py:190} INFO - Failure caused by No module named 'distutils'
[2025-03-09T23:45:39.144+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=real_time_e2e_dag, task_id=extract_data_task, run_id=manual__2025-03-09T17:45:10.269297+00:00, execution_date=20250309T174510, start_date=20250309T174534, end_date=20250309T174539
[2025-03-09T23:45:39.172+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T23:45:39.173+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task extract_data_task (No module named 'distutils'; 34025)
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_temp.py", line 48, in extract_data
    pandas_df = parsed_df.toPandas()
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/pandas/conversion.py", line 86, in toPandas
    require_minimum_pandas_version()
  File "/home/shamim/spark/python/pyspark/sql/pandas/utils.py", line 24, in require_minimum_pandas_version
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
[2025-03-09T23:45:39.230+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T23:45:39.275+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T23:45:39.295+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
