[2025-03-10T00:32:38.071+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:32:38.096+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [queued]>
[2025-03-10T00:32:38.110+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [queued]>
[2025-03-10T00:32:38.110+0600] {taskinstance.py:2867} INFO - Starting attempt 2 of 1
[2025-03-10T00:32:38.132+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-03-09 18:16:22.934679+00:00
[2025-03-10T00:32:38.142+0600] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-10T00:32:38.151+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_e2e_dag', 'extract_data_task', 'manual__2025-03-09T18:16:22.934679+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/RT_data_extract_and_write_to_pg.py', '--cfg-path', '/tmp/tmpw5yk5kmp']
[2025-03-10T00:32:38.152+0600] {standard_task_runner.py:105} INFO - Job 24: Subtask extract_data_task
[2025-03-10T00:32:38.157+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=48437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T00:32:38.158+0600] {standard_task_runner.py:72} INFO - Started process 48629 to run task
[2025-03-10T00:32:38.236+0600] {task_command.py:467} INFO - Running <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [running]> on host shamim-X541UV
[2025-03-10T00:32:38.346+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_e2e_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T18:16:22.934679+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T18:16:22.934679+00:00'
[2025-03-10T00:32:38.348+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T00:32:38.349+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T00:32:38.350+0600] {logging_mixin.py:190} INFO - Current task name:extract_data_task state:running start_date:2025-03-09 18:32:38.096803+00:00
[2025-03-10T00:32:38.350+0600] {logging_mixin.py:190} INFO - Dag name:real_time_e2e_dag and current dag run status:running
[2025-03-10T00:32:38.351+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T00:32:47.907+0600] {java_gateway.py:2273} INFO - Callback Server Starting
[2025-03-10T00:32:47.909+0600] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 44791)
[2025-03-10T00:32:54.733+0600] {clientserver.py:561} INFO - Python Server ready to receive messages
[2025-03-10T00:32:54.737+0600] {clientserver.py:575} INFO - Received command c on object id p0
[2025-03-10T00:35:12.398+0600] {clientserver.py:575} INFO - Received command c on object id p0
[2025-03-10T00:39:55.530+0600] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-10T00:39:55.530+0600] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-03-10T00:39:55.539+0600] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/shamim/airflow_venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_data_extract_and_write_to_pg.py", line 62, in extract_data
    .awaitTermination()
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-10T00:39:55.551+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_data_extract_and_write_to_pg.py", line 62, in extract_data
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-10T00:39:55.556+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T00:39:55.557+0600] {logging_mixin.py:190} INFO - Task start:2025-03-09 18:32:38.096803+00:00 end:2025-03-09 18:39:55.556178+00:00 duration:437.459375
[2025-03-10T00:39:55.558+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_task> dag:<DAG: real_time_e2e_dag> dagrun:<DagRun real_time_e2e_dag @ 2025-03-09 18:16:22.934679+00:00: manual__2025-03-09T18:16:22.934679+00:00, state:running, queued_at: 2025-03-09 18:16:22.965734+00:00. externally triggered: True>
[2025-03-10T00:39:55.558+0600] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-03-10T00:39:55.559+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=real_time_e2e_dag, task_id=extract_data_task, run_id=manual__2025-03-09T18:16:22.934679+00:00, execution_date=20250309T181622, start_date=20250309T183238, end_date=20250309T183955
[2025-03-10T00:39:55.562+0600] {process_utils.py:132} INFO - Sending 15 to group 48629. PIDs of all processes in the group: [48629]
[2025-03-10T00:39:55.563+0600] {process_utils.py:87} INFO - Sending the signal 15 to group 48629
[2025-03-10T00:39:55.563+0600] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-10T00:39:55.636+0600] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/shamim/airflow_venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 328, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3434, in handle_failure
    _handle_failure(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1244, in _handle_failure
    TaskInstance.save_to_db(task_instance, session)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3402, in save_to_db
    ti.get_dagrun().refresh_from_db()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 96, in wrapper
    with create_session() as session:
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 57, in create_session
    session.commit()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1569, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 532, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 809, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 464, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 499, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4015, in visit_insert
    crud_params = crud._get_crud_params(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/crud.py", line 152, in _get_crud_params
    _scan_cols(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/sqlalchemy/sql/crud.py", line 404, in _scan_cols
    _append_param_parameter(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-10T00:39:55.638+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T00:39:55.698+0600] {process_utils.py:80} INFO - Process psutil.Process(pid=48629, status='terminated', exitcode=2, started='00:32:37') (48629) terminated with exit code 2
[2025-03-10T00:39:55.700+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2025-03-10T00:39:55.716+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T00:40:09.133+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:40:09.154+0600] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-03-10T00:40:09.155+0600] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:16:22.934679+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-03-10T00:40:09.156+0600] {local_task_job_runner.py:166} INFO - Task is not able to be run
